services:

  app:
    image: diegomrs/cn2-agendatec:latest
    deploy:
      replicas: 2
    ports:
      - 5010:5000
    environment:
      DATABASE_URL: postgresql://postgres:admin1234@db_stack_db/AgendaTec
    networks:
      - red_swarm

networks:
  red_swarm:
    external: true